machine:
  services:
    - docker
  ruby:
    version: 2.1.5
  environment:
    VAGRANT_DEFAULT_PROVIDER: docker

dependencies:
  cache_directories:
    - ~/.vagrant.d
  pre:
    - wget https://releases.hashicorp.com/vagrant/2.2.0/vagrant_2.2.0_x86_64.deb
    - sudo dpkg -i vagrant_2.2.0_x86_64.deb

compile:
  pre:
    - vagrant up --no-provision
  override:
    - UPDATE_VM_FLAGS=--provision-only vagrant provision

test:
  override:
    - UPDATE_VM_FLAGS=--verify-only vagrant provision
  post:
    - vagrant ssh -c 'cat /home/user/vm-setup/cookbooks/vm/test/junit-report.xml' > $CIRCLE_TEST_REPORTS/junit-report.xml
    - vagrant ssh -c 'cat /home/user/vm-setup/cookbooks/vm/test/test-report.html' > $CIRCLE_TEST_REPORTS/test-report.html
